name: Code quality

on: [ push, pull_request ]

env:
  PHP_VERSION: 8.1

jobs:
  code-quality:
    name: Check code quality

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP version ${{ env.PHP_VERSION }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2

      - name: Get composer cache directory
        id: composer_cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer_cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.PHP_VERSION }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.PHP_VERSION }}-composer-

      - name: Environment check
        run: |
          php --version
          composer --version

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --optimize-autoloader

      - name: Composer normalize
        run: composer run composer:normalize:check

      - name: CGL
        run: composer run cgl:check

      #- name: Psalm
      #  run: composer run psalm

      #- name: PHPStan
      #  run: composer run stan
